### ISSUE TITLE
[Feature] i18n support

### ISSUE THREAD

**Issue by dmvt** [pie-dao/btc.piedao.org#15]
#### User Story

- As an <audience/user>: user
- I want to <action/task>: see the site in my preferred language
- so that <outcome/goal/benefit>: it's easier to read

#### Type

- [X] Enhancement
- [ ] Maintenance
- [ ] Refactor

#### Description

We have a global user base. We should be friendly to them.

#### Solution

@nigeon has a great first pass at https://github.com/pie-dao/btc.piedao.org/pull/4. Unfortunately, the approach taken does not fully support the modular approach of @pie-dao packages. The translations are great, but the text object passed down through the React props (https://github.com/pie-dao/btc.piedao.org/blob/development/src/index.jsx#L54) should be maintained and configured by the i18n solution. 

After reviewing the various options, I believe i18next is the right library to use (https://www.i18next.com/overview/getting-started). If you would prefer to use another, please discuss it in the comments on this issue.

#### Definition of Done

- [ ] the text object is generated by the `i18next` core library (not the react version)
- [ ] at least one language besides english is available
- [ ] a clear structure exists for adding other languages
- [ ] any static English text lingering in the templates is replaced by a key within the text object
- [ ] English is the fallback language

**Comment by nigeon** [comment]
Is there any bounty program?
